#application.yml


---
#로컬 환경.
server:
  port: 8080
  tomcat:
    use-relative-redirects: true

#spring.profiles.include: console-logging

logging:
  level:
    '[org.springframework.web.reactive.function.client.ExchangeFunctions]': DEBUG
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type]' : trace

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      pool-name: HikariPool-market-doctor
      maximum-pool-size: 16
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.106.31.248:3306/smartfactory?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: smartfactory
    password: miracom123!@#
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    open-in-view: false
    #show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: validate
      jdbc:
        order_inserts: true
        order_updates: true
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 1000

  devtools:
    livereload:
      enabled: true

#JWT
jwt:
  header: Authorization
  secret: Zpdlvmzmfl123tmxhrahdj123rmfodlxmgkdnsem123rmfkskxlADSDFQadfQEwQQAdsAZpdlvmzmfl123tmxhrahdj123rmfodlxmgkdnsem123rmfkskxlADSDFQadfQEwQQAdsAZpdlvmzmfl123tmxhrahdj123rmfodlxmgkdnsem123rmfkskxlADSDFQadfQEwQQAdsA
  token-validity-in-second: 129600000





